# Generated by Django 4.0.4 on 2022-05-05 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily_thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField()),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoList.daily')),
            ],
        ),
    ]
